spring:
  config:
    import: optional:file:.env[.properties]
  cache:
    type: redis
    cache-names: redis-cache
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
  application:
    name: java_calendar
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        packagesToScan: ru.minusd.security
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

token:
  signing:
    key: ${JWT_SECRET}

yandex:
  token: ${YANDEX_TOKEN}

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: false
  batch:
    size: 50
  hbm2ddl:
    auto: update
  current:
    session:
      context:
        class: thread

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health